  
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE TABLE IF NOT EXISTS `states`(
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `acronym` varchar(3) NOT NULL,
  `name` varchar(150) NOT NULL,
  `country_id` int(11) NOT NULL,
  PRIMARY KEY(`id`),
  FOREIGN KEY (country_id) REFERENCES countries(id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=79 ;

INSERT INTO states VALUES
(1,'AL','Alabama', 2),
(2,'AK','Alaska', 2),
(3,'AZ','Arizona', 2),
(4,'AR','Arkansas', 2),
(5,'CA','California', 2),
(6,'CO','Colorado', 2),
(7,'CT','Connecticut', 2),
(8,'DE','Delaware', 2),
(9,'DC','District of Columbia', 2),
(10,'FL','Florida', 2),
(11,'GA','Georgia', 2),
(12,'HI','Hawaii', 2),
(13,'ID','Idaho', 2),
(14,'IL','Illinois', 2),
(15,'IN','Indiana', 2),
(16,'IA','Iowa', 2),
(17,'KS','Kansas', 2),
(18,'KY','Kentucky', 2),
(19,'LA','Louisiana', 2),
(20,'ME','Maine', 2),
(21,'MD','Maryland', 2),
(22,'MA','Massachusetts', 2),
(23,'MI','Michigan', 2),
(24,'MN','Minnesota', 2),
(25,'MS','Mississippi', 2),
(26,'MO','Missouri', 2),
(27,'MT','Montana', 2),
(28,'NE','Nebraska', 2),
(29,'NV','Nevada', 2),
(30,'NH','New Hampshire', 2),
(31,'NJ','New Jersey', 2),
(32,'NM','New Mexico', 2),
(33,'NY','New York', 2),
(34,'NC','North Carolina', 2),
(35,'ND','North Dakota', 2),
(36,'OH','Ohio', 2),
(37,'OK','Oklahoma', 2),
(38,'OR','Oregon', 2),
(39,'PA','Pennsylvania', 2),
(40,'PR','Puerto Rico', 2),
(41,'RI','Rhode Island', 2),
(42,'SC','South Carolina', 2),
(43,'SD','South Dakota', 2),
(44,'TN','Tennessee', 2),
(45,'TX','Texas', 2),
(46,'UT','Utah', 2),
(47,'VT','Vermont', 2),
(48,'VA','Virginia', 2),
(49,'WA','Washington', 2),
(50,'WV','West Virginia', 2),
(51,'WI','Wisconsin', 2),
(52,'WY','Wyoming', 2),
(53,'AC','Acre', 1),  
(54,'AL','Alagoas', 1),  
(55,'AM','Amazonas', 1),
(56,'AP','Amapá', 1),
(57,'BA','Bahia', 1),
(58,'CE','Ceará', 1),
(59,'DF','Distrito Federal', 1),
(60,'ES','Espírito Santo', 1),
(61,'GO','Goiás', 1),
(62,'MA','Maranhão', 1),
(63,'MG','Minas Gerais', 1),
(64,'MS','Mato Grosso do Sul', 1),
(65,'MT','Mato Grosso', 1),
(66,'PA','Pará', 1),
(67,'PB','Paraíba', 1),
(68,'PE','Pernambuco', 1),
(69,'PI','Piauí', 1),
(70,'PR','Paraná', 1),
(71,'RJ','Rio de Janeiro', 1),
(72,'RN','Rio Grande do Norte', 1),
(73,'RO','Rondônia', 1),
(74,'RR','Roraima', 1),
(75,'RS','Rio Grande do Sul', 1),
(76,'SC','Santa Catarina', 1),
(77,'SE','Sergipe', 1),
(78,'SP','São Paulo', 1),
(79,'TO','Tocantins', 1);